spring.application.name=Ecommerce

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Redis Caching
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# JWT
security.jwt.secret=${JWT_SECRET}

# Stripe
stripe.api.key=${STRIPE_SECRET_KEY:}

# Actuator Monitoring
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always

# Resilience4j Configs
resilience4j.circuitbreaker.instances.stripeService.sliding-window-size=10
resilience4j.circuitbreaker.instances.stripeService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.stripeService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.stripeService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.stripeService.failure-rate-threshold=50

resilience4j.ratelimiter.instances.loginRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.loginRateLimiter.limit-refresh-period=1m
resilience4j.ratelimiter.instances.loginRateLimiter.timeout-duration=500ms
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=20000
